name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11-jdk]
    container:
      image: openjdk:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        run: ./gradlew checkLicenses build --stacktrace